name: CI-CD

on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      
      - name: Obter o codigo do projeto
        uses: actions/checkout@v4
        
      - name: Autenticar no Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          
      - name: Construção e push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            rolesosi/fake-shop:latest
            rolesosi/fake-shop:v${{github.run_number}}
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Obter o codigo do projeto
        uses: actions/checkout@v4
      - name: Autenticar na AWS
        uses: aws-actions/configure_aws_credentials@v4
        with:
          aws-acess-key-id: ${{secrets.AWS_ACESS_KEY_ID}}
          aws-acess-access-key: ${{secrets.AWS_ACESS_ACCESS_KEY}}
          aws-region: us-east-1
      - name: Configuraro kubectl
        run: echo "Executandoo o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executandoo o comando kubectl apply"      
